---
sets:
  'centos-66-x64':
    nodes:
      "main.foo.vm":
        prefab: 'centos-66-x64'
  'debian-6011-x64':
    nodes:
      "main.foo.vm":
        prefab: 'debian-6011-x64'
  'debian-78-x64':
    nodes:
      "main.foo.vm":
        prefab: 'debian-78-x64'
  'debian-78-i386':
    nodes:
      "main.foo.vm":
        prefab: 'debian-78-i386'
  'ubuntu-server-1204-x64':
    nodes:
      "main.foo.vm":
        prefab: 'ubuntu-server-1204-x64'
  'ubuntu-server-1404-x64':
    nodes:
      "main.foo.vm":
        prefab: 'ubuntu-server-1404-x64'
  'ubuntu-server-1604-x64':
    nodes:
      "main.foo.vm":
        prefab: 'ubuntu-server-1604-x64'
